proxy:
  image: rafaeltuelho/mod_cluster:1.3.2.Final
  environment:
    - MODCLUSTER_PORT=6666
    - MODCLUSTER_ADVERTISE=On
    - MODCLUSTER_NET=172.
    - MODCLUSTER_ADVERTISE_GROUP=224.0.1.105:23364
  ports:
   - "80/tcp"
   - "6666/tcp"
  hostname: proxy
postgres:
  image: postgres
  environment:
   - POSTGRES_DATABASE=keycloak
   - POSTGRES_USER=keycloak
   - POSTGRES_PASSWORD=password
   - POSTGRES_ROOT_PASSWORD=password
  hostname: postgres
keycloak1:
  image: jboss/keycloak-ha-postgres
  environment:
   - KEYCLOAK_USER=admin
   - KEYCLOAK_PASSWORD=CHANGE@ME
   - POSTGRES_DATABASE=keycloak
   - POSTGRES_USER=keycloak
   - POSTGRES_PASSWORD=password
  expose:
   - "8080/tcp"
   - "8009/tcp"
  ports:
   - "8080"
  links:
   - postgres
  hostname: keycloak1
  command: ["-b", "0.0.0.0", "-bprivate=keycloak1", "-bmanagement=0.0.0.0", "--server-config", "standalone-ha.xml"]
keycloak2:
  image: jboss/keycloak-ha-postgres
  environment:
   - KEYCLOAK_USER=admin
   - KEYCLOAK_PASSWORD=CHANGE@ME
   - POSTGRES_DATABASE=keycloak
   - POSTGRES_USER=keycloak
   - POSTGRES_PASSWORD=password
  expose:
   - "8080/tcp"
   - "8009/tcp"
  ports:
   - "8080"
  links:
   - postgres
  hostname: keycloak2
  command: ["-b", "0.0.0.0", "-bprivate=keycloak2", "-bmanagement=0.0.0.0", "--server-config", "standalone-ha.xml"]
